### ISSUE TITLE
Warning by calling deprecated methods

### ISSUE THREAD

**Issue by astj** [aereal/homebrew-tsocks#1]
With recent Homebrew's update, some old methods became deprecated and it begins producing warning messages.

```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/aereal/homebrew-tsocks/tsocks.rb:9:in `<class:Tsocks>'
Please report this to the aereal/tsocks tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/aereal/homebrew-tsocks/tsocks.rb:9:in `<class:Tsocks>'
Please report this to the aereal/tsocks tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/aereal/homebrew-tsocks/tsocks.rb:9:in `<class:Tsocks>'
Please report this to the aereal/tsocks tap!

Warning: Calling MacOS.xcode_version is deprecated!
Use MacOS::Xcode.version instead.
/usr/local/Library/Taps/aereal/homebrew-tsocks/tsocks.rb:10:in `<class:Tsocks>'
Please report this to the aereal/tsocks tap!
```

Maybe just changing method names will work fine, though I haven't confirmed.

**Comment by aereal** [comment]
Thanks https://github.com/aereal/homebrew-tsocks/pull/2
